version: '3'
services:

  ### Emby #######################################################################
  emby:
    image: linuxserver/emby:beta
    container_name: emby
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${APP_BASE_DIR}/emby/config:/config
      - ${MEDIA_DIR}:/share/media
    ports:
      - ${EMBY_PORT}:8096
      - ${EMBY_PORT_HTTPS}:8920
    devices:
      - ${DVI_DIR}:/dev/dri
    restart: unless-stopped
    envfile:
      - stack.env

  ### Jellyseerr #######################################################################
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - ${JELLYSEERR_PORT}:5055
    volumes:
      - ${APP_BASE_DIR}/jellyseerr/config:/app/config
    restart: unless-stopped
    envfile:
      - stack.env

  ### Plex #######################################################################
  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
      - ADVERTISE_IP=https://plex.gamersgu.cn:12443
    ports:
      - ${PLEX_PORT}:32400
    volumes:
      - ${APP_BASE_DIR}/plex-server/config:/config
      - ${MEDIA_DIR}:/share/media
      - /mnt/media/music/music:/share/media/music
    devices:
      - ${DVI_DIR}:/dev/dri
    restart: unless-stopped
    envfile:
      - stack.env

  ### Overseerr #######################################################################
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APP_BASE_DIR}/overseerr/config:/config
    ports:
      - ${OVERSEERR_PORT}:5055
    restart: unless-stopped
    envfile:
      - stack.env
      
  ### Tautulli #######################################################################
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ${APP_BASE_DIR}/tautulli/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${TAUTULLI_PORT}:8181
    envfile:
      - stack.env  



  ### Nextcloud #######################################################################
  nextcloud-db:
    container_name: hexo
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      -  ${APP_BASE_DIR}/nextcloud/storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=JntoFg8o
      - MYSQL_PASSWORD=JntoFg8o
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    envfile:
      - stack.env
      
  nextcloud-redis:
    image: redis:alpine
    restart: always
  nextcloud-app:
    image: nextcloud:fpm
    restart: always
    links:
      - nextcloud-db
    volumes:
      - ${APP_BASE_DIR}/nextcloud/config:/var/www/html
      - ${APP_BASE_DIR}/nextcloud/data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=JntoFg8o
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - OVERWRITEHOST=${NEXTCLOUD_OVERWRITEHOST}
      - OVERWRITEPROTOCOL=${NEXTCLOUD_OVERWRITEPROTOCOL}
      - OVERWRITECLIURL=${NEXTCLOUD_OVERWRITECLIURL}
    envfile:
      - stack.env

  nextcloud-cron:
    image: nextcloud:fpm
    restart: always
    volumes:
      - ${APP_BASE_DIR}/nextcloud/config:/var/www/html:z
      - ${APP_BASE_DIR}/nextcloud/data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    envfile:
      - stack.env

  nextcloud-web:
    image: nginx
    restart: always
    ports:
      - ${NEXTCLOUD_PORT}:80
    links:
      - nextcloud-app
    volumes:
      -  ${APP_BASE_DIR}/nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - nextcloud-app
    envfile:
      - stack.env

  ### Homepage #######################################################################
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - ${APP_BASE_DIR}/homepage/config:/app/config # Make sure your local config directory 
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro # (optional) For docker integrations
      - /:/srv
      - ${APP_BASE_DIR}/homepage/config/images:/app/public/images
      - ${APP_BASE_DIR}/homepage/config/icons:/app/public/icons
    envfile:
      - stack.env

  ### Swag #######################################################################
  swag:
    image: linuxserver/swag:latest
    container_name: swag
    environment:
      - TZ=${TZ}
      - URL=${SWAG_URL}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - VALIDATION=${SWAG_VALIDATION}
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
    volumes:
      - ${APP_BASE_DIR}/swag:/config
      - ${APP_BASE_DIR}/swag-ssl:/swag-ssl
    ports:
      - ${SWAG_PORT_HTTP}:80
      - ${SWAG_PORT_HTTPS}:443
    restart: unless-stopped
    envfile:
      - stack.env
  
  ### Kodexplorer #######################################################################
  kodexplorer:
    image: yangxuan8282/kodexplorer:latest
    container_name: kodexplorer
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${APP_BASE_DIR}/kodbox/data:/var/www/html
      - /:/srv
    ports:
      - ${KODX_PORT}:80
    restart: unless-stopped

  ### Hexo #######################################################################
  hexo:
    container_name: hexo
    image: bloodstar/hexo:latest
    hostname: hexo
    ports:
      - ${HEXO_PORT}:4000
    volumes:
      - ${APP_BASE_DIR}/hexo:/app
    environment:
      - PUID=${PGID}
      - PGID=${PGID}
      - TZ=${TZ}
      - GIT_USER=${HEXO_GIT_USER}
      - GIT_EMAIL=${HEXO_GIT_EMAIL}
    envfile:
      - stack.env
    restart: always


