version: '2'

services:
  ### Nextcloud #######################################################################
  nextcloud-db:
    container_name: hexo
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      -  ${APP_BASE_DIR}/nextcloud/storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=JntoFg8o
      - MYSQL_PASSWORD=JntoFg8o
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  nextcloud-redis:
    image: redis:alpine
    restart: always
  nextcloud-app:
    image: nextcloud:fpm
    restart: always
    links:
      - nextcloud-db
    volumes:
      - ${APP_BASE_DIR}/nextcloud/config:/var/www/html
      - ${APP_BASE_DIR}/nextcloud/data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=JntoFg8o
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - OVERWRITEHOST=${NEXTCLOUD_OVERWRITEHOST}
      - OVERWRITEPROTOCOL=${NEXTCLOUD_OVERWRITEPROTOCOL}
      - OVERWRITECLIURL=${NEXTCLOUD_OVERWRITECLIURL}
  nextcloud-cron:
    image: nextcloud:fpm
    restart: always
    volumes:
      - ${APP_BASE_DIR}/nextcloud/config:/var/www/html:z
      - ${APP_BASE_DIR}/nextcloud/data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis
  nextcloud-web:
    image: nginx
    restart: always
    ports:
      - ${NEXTCLOUD_PORT}:80
    links:
      - nextcloud-app
    volumes:
      -  ${APP_BASE_DIR}/nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - nextcloud-app